version: '3.8'

services:
  nginx:
    image: nginx:1.23
    networks:
      - nginx-upstreams
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - 8001:8000
    depends_on:
      - app-first
      - app-second

  app-first:
    networks:
      - nginx-upstreams
    build:
      context: ../../apps/aspnet-hit-counter
    environment:
      ASPNETCORE_URLS: "http://+:8000" 

  app-second:
    networks:
      - nginx-upstreams
    build:
      context: ../../apps/aspnet-hit-counter
    environment:
      ASPNETCORE_URLS: "http://+:8000" 

networks:
  nginx-upstreams: