version: '3.8'

services:
  node:
    build:
      context: ../
      dockerfile: volumes/Dockerfile-node
      args:
        SOURCE: "./apps/simple-express"
        GID: ${GID}
        UID: ${UID}
    volumes:
        - "../shared:/home/node/app/shared"
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  static:
    build:
      context: ../
      dockerfile: volumes/Dockerfile-node
      args:
        SOURCE: "./apps/static-server-express"
        GID: ${GID}
        UID: ${UID}
    volumes:
      - "../shared:/home/node/app/shared"
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    depends_on:
      - node
