version: '3.8'

name: elk

services:
  fake-logger:
    image: willsenabr/fake-logger
    logging:
      driver: gelf
      options:
        tag: dev
        gelf-address: udp://localhost:12201
    environment:
      DELAY: 1000
    depends_on:
      - logstash

  elasticsearch:
    image: bitnami/elasticsearch:8
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/bitnami/elasticsearch/data
    environment:
        discovery.type: single-node
        ELASTICSEARCH_PORT_NUMBER: 9200
        ELASTICSEARCH_CLUSTER_NAME: docker-elk
        ES_JAVA_OPTS: -Xms512m -Xmx512m

  logstash:
    image: bitnami/logstash:7
    ports:
      - "12201:12201/udp"
      - "5044:5044"
    environment:
      LOGSTASH_PIPELINE_CONF_FILENAME: "logstash_docker.conf"
    volumes:
      - ./assets/logstash/pipeline:/bitnami/logstash/pipeline
    depends_on:
      - elasticsearch

  kibana:
    image: bitnami/kibana:7
    ports:
      - 5601:5601
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
    volumes:
      - kibana-data:/bitnami/kibana
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
  kibana-data:

networks:
  default:
    name: elk