version: '3.8'

name: test-build

services:
    busybox:
      build: ./
      command: curl -I http://www.example.org

    label:
      build:
        context: ../build/samples/
        dockerfile: label.Dockerfile
        labels:
          ENV_TEST: true
     
    args:
      build:
        context: ../build/samples/
        dockerfile: args.Dockerfile
        args:
          VERSION: "edge"
