version: '3.8'

name: test-healthcheck

services:
    slow-redis:
      image: redis
      entrypoint: /bin/sh
      command: -c "sleep 30 && redis-server"
      healthcheck:
        test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
        interval: 10s
        timeout: 3s
        start_period: 1s
        
