version: '3.8'

name: test-volumes

services:
    busybox-volume:
        build: ./
        command: sleep 365d
        volumes:
            - local-data:/tmp/data

    busybox-mount-volume:
        build: ./
        command: sleep 365d
        volumes:
            - /tmp/data:/tmp/data


volumes:
    local-data: